# Generated by Django 4.0.6 on 2022-08-02 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='market.genre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='oblojka',
            field=models.ImageField(blank=True, null=True, upload_to='media/books/'),
        ),
    ]
