# Generated by Django 4.1 on 2022-08-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='oblojka',
            field=models.ImageField(blank=True, null=True, upload_to='books/'),
        ),
    ]
